version: "3.8"
services:
  service:
    container_name: musspring_backend
    build: .
    ports:
      - "8080:8080"
    env_file:
      - .env
    depends_on:
      - database
    volumes:
      - ./data:/back_info
      - ./data/files:/storage

  database:
    container_name: musspring_database
    image: postgres:15-alpine
    ports:
      - "5433:5432"
    env_file:
      - .env
