server:
  port: 8080

spring:
  datasource:
    # Settings for connecting to the local DB
#    url: jdbc:postgresql://localhost:5432/musspring
#    username: postgres
#    password: 1994R

    # Settings for connecting to the DB in Docker
    url: jdbc:postgresql://musspring_database:5432/${POSTGRES_DB}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}

    driver-class-name: org.postgresql.Driver
  jpa:
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQL10Dialect
    generate-ddl: false
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB

upload:
  # Path to the directory in container
  path: /storage
  # Path to the local directory (uncomment if you want to use local storage)
  # The directory in resources folder of Spring Boot project
#  path: ${user.dir}/src/main/resources/storage

logging:
  file:
    name: /back_info/musspring_backend.log

admin:
  username: ${ADMIN_USERNAME}
  password: ${ADMIN_PASSWORD}
  email: ${ADMIN_EMAIL}
  real_name: ${ADMIN_REAL_NAME}
  second_name: ${ADMIN_SECOND_NAME}

# Path to the project from the root of OS (uncomment if you want to use local storage)
#user:
#  dir: