server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/musspring_database
    username: service
    password: 197319792001

    driver-class-name: org.postgresql.Driver
  jpa:
    database: postgresql
    generate-ddl: false
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB