server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/musspring
    username: postgres
    password: 1994R
    driver-class-name: org.postgresql.Driver
  jpa:
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQL10Dialect
    generate-ddl: true

upload:
  path: C:/Users/mikha/Documents/МИРЭА/Разработка серверных частей интернет ресурсов/Курсач/MusSpring-backend/src/main/resources/static/uploads