server:
  port: 8080

spring:
  datasource:
    # Settings for connecting to the local DB
#    url: jdbc:postgresql://localhost:5432/musspring
#    username: postgres
#    password: 1994R

    # Settings for connecting to the DB in Docker
    url: jdbc:postgresql://${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}

    driver-class-name: org.postgresql.Driver
  jpa:
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQL10Dialect
    generate-ddl: false
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB

upload:
  path: ${DATA_DIR}

download:
  path: ${DATA_DIR}

logging:
  file:
    name: /back_info/musspring_backend.log

admin:
  username: ${ADMIN_USERNAME}
  password: ${ADMIN_PASSWORD}
  email: ${ADMIN_EMAIL}
  real_name: ${ADMIN_REAL_NAME}
  second_name: ${ADMIN_SECOND_NAME}